AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'unicode_exam_api

  Sample SAM Template for unicode_exam_api

  '
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Applications
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: appid
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: appid
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: ApplicationsTable
  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-407fbfb3/myprefix/8ff312c0c9e8035cf005ef4c538e6d44
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        CreateApplication:
          Type: Api
          Properties:
            Path: /api/v1/application
            Method: post
    Metadata:
      SamResourceId: CreateApplicationFunction
  GetApplicationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-407fbfb3/myprefix/048476faa46f6ad6fb1b4203aa227b1c
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        GetApplications:
          Type: Api
          Properties:
            Path: /api/v1/saved/
            Method: get
    Metadata:
      SamResourceId: GetApplicationsFunction
  EditApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-407fbfb3/myprefix/4a939ec183a815a0679a99a1d16d1641
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        EditApplication:
          Type: Api
          Properties:
            Path: /api/v1/application/{applicationid}
            Method: put
    Metadata:
      SamResourceId: EditApplicationFunction
  GetApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-407fbfb3/myprefix/422b6dd35ed6fcbfc565aa94eac64098
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        GetApplication:
          Type: Api
          Properties:
            Path: /api/v1/application/{applicationid}
            Method: get
    Metadata:
      SamResourceId: GetApplicationFunction
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-407fbfb3/myprefix/c6ce8fa8b5a97dd022ecd006536eb5a4
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      SamResourceId: HelloWorldFunction
Outputs:
  TableName:
    Description: The name of the DynamoDB table
    Value: !Ref ApplicationsTable
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
