AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'unicode_exam_api

  Sample SAM Template for unicode_exam_api

  '
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  UnicodeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Unicode
      AttributeDefinitions:
      - AttributeName: char
        AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      KeySchema:
      - AttributeName: char
        KeyType: HASH
    Metadata:
      SamResourceId: UnicodeTable
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Applications
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: appid
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: appid
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: ApplicationsTable
  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlessadminbucket/d1aeb9467b408aa507bb0d6ef8ebc0f0
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        CreateApplication:
          Type: Api
          Properties:
            Path: /api/v1/application
            Method: post
    Metadata:
      SamResourceId: CreateApplicationFunction
  GetApplicationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlessadminbucket/048476faa46f6ad6fb1b4203aa227b1c
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        GetApplications:
          Type: Api
          Properties:
            Path: /api/v1/saved/
            Method: get
    Metadata:
      SamResourceId: GetApplicationsFunction
  EditApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlessadminbucket/4a939ec183a815a0679a99a1d16d1641
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        EditApplication:
          Type: Api
          Properties:
            Path: /api/v1/application/{applicationid}
            Method: put
    Metadata:
      SamResourceId: EditApplicationFunction
  GetApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlessadminbucket/422b6dd35ed6fcbfc565aa94eac64098
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ApplicationsTable
      Events:
        GetApplication:
          Type: Api
          Properties:
            Path: /api/v1/application/{applicationid}
            Method: get
    Metadata:
      SamResourceId: GetApplicationFunction
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlessadminbucket/66a43403ed45e1ba3894d25fc108a14e
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      SamResourceId: HelloWorldFunction
  UnicodeInfoFunction:
    Metadata:
      BuildMethod: python3.8
      BuildCommand: pip install -r requirements.txt -t get_char_info/
      SamResourceId: UnicodeInfoFunction
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UnicodeTable
      CodeUri: s3://serverlessadminbucket/81a259fcb8a79acc262a5f3f01c7a1ab
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        UnicodeInfo:
          Type: Api
          Properties:
            Path: /api/v1/unicode/{char}
            Method: get
