AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  unicode_exam_api

  Sample SAM Template for unicode_exam_api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Applications
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: appid
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: appid
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_application/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        CreateApplication:
          Type: Api
          Properties:
            Path: /api/v1/application
            Method: post

  GetApplicationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_applications/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        GetApplications:
          Type: Api
          Properties:
            Path: /api/v1/saved/
            Method: get
  EditApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: edit_application/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        EditApplication:
          Type: Api
          Properties:
            Path: /api/v1/application/{applicationid}
            Method: put
  GetApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_application/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        GetApplication:
          Type: Api
          Properties:
            Path: /api/v1/application/{applicationid}
            Method: get
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
